# This workflow builds a Docker image from the Dockerfile and publishes the
# image to Docker Hub. How the image tags are chosen is documented here:
# https://github.com/samply/github-workflows/blob/main/.github/workflows/docker-ci.yml
#
# This file is copied and adapted from:
# https://github.com/samply/.github/blob/main/workflow-templates/docker-ci-template.yml

name: Docker CI

on:
  push:
    branches:
      - main
      - develop
    # Build when a new version is tagged
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - develop
  schedule:
    # Build every night at 1am
    - cron: "0 1 * * *"
jobs:
  build:
    # This workflow defines how a samply docker image is built, tested and published.
    # Visit: https://github.com/samply/github-workflows/blob/main/.github/workflows/docker-ci.yml, for more information
    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
    with:
      # The Docker Hub Repository you want eventually push to, e.g samply/share-client
      image-name: "samply/siorgp-public-dashboard"
      # Where to push your images ("dockerhub", "ghcr", "both" or "none")
      push-to: dockerhub
    # This passes the secrets from calling workflow to the called workflow
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}